language: python
python:
    - 3.7
install:
    - pip install -r requirements.txt
script:
    - python manage.py test
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: lunchscraper
  run: python manage.py migrate
  on: master