# Generated by Django 3.0.7 on 2020-06-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subscribed', models.DateTimeField()),
                ('token', models.CharField(max_length=24)),
                ('preferences', models.ManyToManyField(to='restaurants.Restaurant')),
            ],
        ),
    ]
